### PR TITLE
RWEB-7629: checking key validity and quoting special characters in values

### LINKED ISSUE #70: Value with space and colon doubly quoted with single quotes
With `gorson get --format env /DEV/PBSORG > .env` running against `pbs-digi-preprod`, I get a KV pair that looks like this:
`PBSORG_BADGE_CTA_HEADLINE=''COMPLETE COVERAGE:''`

That causes bash to choke when sourcing the file:
`/etc/pbsorg/.env: line 29: COVERAGE:: command not found.`

The full value in the parameter store is `COMPLETE COVERAGE:`.  Odd that Gorson is putting two pairs of single quotes around it, as there are many other values with whitespace that aren't treated as such.

### PR DESCRIPTION
**Pull request by socketbox**
Kind of cheating here: rather than troubleshoot the regex at the core of the `-f env` option, I sidestepped it and used already-working cod in `bash.go` to accomplish the same thing. 

Certainly open to improving the regex in `env.Marshal` rather than throwing it away.

Fixes #70

### CODE REVIEW

**Comment by socketbox** [comment]
Hmm. I run `./script/test.sh` locally, and everything passes -- though I'm on go version 1.19.3

**Comment by yhakbar** [comment]
I'll try to get the tests to work in GHA, but I'm not for this change @socketbox . 

It's a breaking change we shouldn't make in my opinion, as the `env` format should be a standard `.env` file with key-value pairs separated by a `=`. We can add an extra `bash` format that exports each variable, but that shouldn't really be necessary either. 

I think the most productive thing would be to try to reproduce the error you were getting in a test-case and try to red/green refactor our way to a working `env` value for the `-f` flag.

**Review by yhakbar — CHANGES_REQUESTED** [review]
I already left a comment, but can't put this in request changes without another one :)

**Review by socketbox — COMMENTED** [review]
Suggestions incorporated into latest revision

**Review by yhakbar — APPROVED** [review]

**Pull request merged**
